export const cartActionTypes = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_QUANTITY: 'REMOVE_QUANTITY',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  REMOVE_ALL_ITEMS_FROM_CART: 'REMOVE_ALL_ITEMS_FROM_CART',
}
